#!/bin/bash

# ------------------------------------------------------------------------------
# html_generator.sh - Second Script - HTML Table Presentation of Image Thumbnails
# ------------------------------------------------------------------------------

output_file="index.html"
author="Mohamed A. Elsherif (6378374)"
created_at=$(date "+%Y-%m-%d %H:%M:%S")

# Start HTML structure
{
echo "<!DOCTYPE html>"
echo "<html lang=\"en\">"
echo "<head>"
echo "  <meta charset=\"UTF-8\">"
echo "  <title>Image Gallery</title>"
echo "  <style>"
echo "    table { width: 100%; border-collapse: collapse; }"
echo "    td { border: 1px solid #ccc; padding: 10px; text-align: center; }"
echo "    img { max-width: 100px; height: auto; }"
echo "  </style>"
echo "</head>"
echo "<body>"
echo "  <h1>Table Presentation of Image Thumbnails</h1>"
echo "  <p><strong>Generated by:</strong> $author</p>"
echo "  <p><strong>Generated on:</strong> $created_at</p>"
echo "  <table>"
echo "    <tr><th>Thumbnail</th><th>Filename</th><th>Size</th><th>Resolution</th></tr>"
} > "$output_file"

# Process each original image (excluding thumbnails)
for img in *.*; do
    # Skip thumbnails
    [[ "$img" == *.small.jpg ]] && continue

    # Find thumbnail
    base_name="${img%.*}"
    thumb="${base_name}.small.jpg"
    [[ -f "$thumb" ]] || continue

    # Extract metadata
    size=$(stat -f%z "$img")
    readable_size=$(numfmt --to=iec "$size" 2>/dev/null || echo "${size} B")
    resolution=$(exiftool -s3 -ImageSize "$img")

    # Write HTML row
    {
    echo "    <tr>"
    echo "      <td><a href=\"$img\"><img src=\"$thumb\" alt=\"Thumbnail\"></a></td>"
    echo "      <td><a href=\"$img\">$img</a></td>"
    echo "      <td>$readable_size</td>"
    echo "      <td>$resolution</td>"
    echo "    </tr>"
    } >> "$output_file"
done

# Close HTML
{
echo "  </table>"
echo "</body>"
echo "</html>"
} >> "$output_file"

echo "HTML file '$output_file' created successfully."
echo "And can be found here:"
tree -L 1

############################## End of Script ##############################
# Elsherif, Mohamed A. (6378374)
# 2025
# =================================